module.exports = {
  purge: [],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        midnight: '#60266A',
        black: '#000000',
        lavender: '#E3B3EC',
        sunlight: '#F4EA7C',
        rose: '#B93962',
        lilac: '#BA89F7',
        silver: '#D9D9D9',
        skyblue: '#CAF2FF',
        steel: '#A7A7A7',
        ink: '#2A2D3E',
        ruby: '#CC1C18',
        gold: '#EDCF2A',
        sea: '#3C6F82',
        crimson: '#B30008',
        magenta: '#CA0044',
        cobalt: '#2176BB',
        carrot: '#FF6015',
        red: '#FF0000',
        twitter: '#1DA1F2',
        mint: '#8EDD97',
        charcoal: '#2F3241',
        azure: '#58C0FF',
        graphite: '#212332',
        amethyst: '#B592FF',
        plum: '#3B2D57',
        turquoise: '#04B5C0',
        salmon: '#F96167',
        amber: '#FFB800',
        coral: '#FF5F5F',
        sapphire: '#3380F2',
        honey: '#FFE55F',
        jade: '#5FFF6F',
        slate: '#2D3036',
        obsidian: '#46484D',
        onyx: '#13141A',
      },
      boxShadow: {
        default: '0 4px 8px 2px rgba(0, 0, 0, 0.25)',
      },
      fontFamily: {
        sans: ['Helvetica', 'Roboto', 'Arial', 'sans-serif'],
        cursive: ['RubikVinyl', 'sans-serif'],
        serif: ['Mukta'],
        mono: ['"Fira Code"', 'ui-monospace'],
        display: ['Oswald'],
      },
      animation: {
        fadeIn: 'fadeIn .3s ease-in-out',
        animateWidthResize: 'animateWidthResize 4s linear infinite alternate both',
      },
      keyframes: () => ({
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        animateWidthResize: {
          '0%': { width: '10%' },
          '100%': { width: '100%' },
        },
      }),
    },
  },
  variants: {},
  plugins: [],
};
